signal:
    nclass: 1
    nlayer: 1
    num_heads: 1
    hidden_dim: 16
    epoch: 2000
    lr: 0.01
    weight_decay: 0.0
    tran_dropout: 0.0
    feat_dropout: 0.0
    prop_dropout: 0.0
    norm: 'none'
    nonlinear: 'GELU'
    patience: 200
    residual: 'True'
cora:
    graph_norm_type: 'laplacian'
    pair_norm_type: 'laplacian'
    pair_dis_type: 'cosine'
    pair_trunc: 'all'

    nclass: 7
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 2000
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.2
    feat_dropout: 0.8
    prop_dropout: 0.4
    norm: 'none'
    nonlinear: 'ReLU'
    patience: 200
    residual: 'True'
citeseer:
    graph_norm_type: 'laplacian'
    pair_norm_type: 'laplacian'
    pair_dis_type: 'cosine'
    pair_trunc: -1

    nclass: 6
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 2000
    lr: 0.0002
    weight_decay: 0.0001
    tran_dropout: 0.0
    feat_dropout: 0.8
    prop_dropout: 0.5
    norm: 'none'
    nonlinear: 'GELU'
    patience: 200
    residual: 'True'
photo:
    nclass: 8
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0001
    tran_dropout: 0.2
    feat_dropout: 0.5
    prop_dropout: 0.2
    norm: 'none'
    nonlinear: 'GELU'
    patience: 200
    residual: 'False'
arxiv:
    nclass: 40
    nlayer: 1
    num_heads: 1
    hidden_dim: 512
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
    nonlinear: 'GELU'
    patience: 200
    residual: 'True'
chameleon:
    nclass: 5
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0005
    tran_dropout: 0.2
    feat_dropout: 0.8
    prop_dropout: 0.2
    norm: 'none'
    nonlinear: 'GELU'
    patience: 1000
    residual: 'True'
squirrel:
    nclass: 5
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 5000
    lr: 0.001
    weight_decay: 0.0001
    tran_dropout: 0.1
    feat_dropout: 0.4
    prop_dropout: 0.4
    norm: 'none'
    nonlinear: 'ReLU'
    patience: 4000
    residual: 'True'
actor:
    nclass: 5
    nlayer: 3
    num_heads: 1
    hidden_dim: 32
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0001
    tran_dropout: 0.5
    feat_dropout: 0.8
    prop_dropout: 0.5
    norm: 'none'
    nonlinear: 'GELU'
    patience: 200
    residual: 'True'
penn:
    nclass: 2
    nlayer: 1
    num_heads: 1
    hidden_dim: 64
    epoch: 2000
    lr: 0.001
    weight_decay: 0.001
    tran_dropout: 0.0
    feat_dropout: 0.4
    prop_dropout: 0.4
    norm: 'batch'
    nonlinear: 'GELU'
    patience: 200
    residual: 'True'
