signal:
    nclass: 1
    nlayer: 1
    num_heads: 1
    hidden_dim: 16
    epoch: 2000
    lr: 0.01
    weight_decay: 0.0
    tran_dropout: 0.0
    feat_dropout: 0.0
    prop_dropout: 0.0
    norm: 'none'
    nonlinear: 'GELU'
    patience: 200
cora:
    nclass: 7
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 2000
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.2
    feat_dropout: 0.8
    prop_dropout: 0.4
    norm: 'none'
    nonlinear: 'ReLU'
    patience: 200
citeseer:
    nclass: 6
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 2000
    lr: 0.0002
    weight_decay: 0.0001
    tran_dropout: 0.0
    feat_dropout: 0.8
    prop_dropout: 0.5
    norm: 'none'
    nonlinear: 'GELU'
    patience: 200
photo:
    nclass: 8
    nlayer: 2
    num_heads: 2
    hidden_dim: 64
    epoch: 2000
    lr: 0.0002
    weight_decay: 0.0001
    tran_dropout: 0.2
    feat_dropout: 0.3
    prop_dropout: 0.2
    norm: 'none'
    nonlinear: 'GELU'
    patience: 200
arxiv:
    nclass: 40
    nlayer: 1
    num_heads: 1
    hidden_dim: 512
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
    nonlinear: 'GELU'
    patience: 200
chameleon:
    nclass: 5
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0005
    tran_dropout: 0.2
    feat_dropout: 0.4
    prop_dropout: 0.5
    norm: 'none'
    nonlinear: 'GELU'
    patience: 200
squirrel:
    nclass: 5
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 5000
    lr: 0.001
    weight_decay: 0.0001
    tran_dropout: 0.1
    feat_dropout: 0.4
    prop_dropout: 0.4
    norm: 'none'
    nonlinear: 'ReLU'
    patience: 4000
actor:
    nclass: 5
    nlayer: 3
    num_heads: 1
    hidden_dim: 32
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0001
    tran_dropout: 0.5
    feat_dropout: 0.8
    prop_dropout: 0.5
    norm: 'none'
    nonlinear: 'GELU'
    patience: 200
penn:
    nclass: 2
    nlayer: 1
    num_heads: 1
    hidden_dim: 64
    epoch: 2000
    lr: 0.001
    weight_decay: 0.001
    tran_dropout: 0.0
    feat_dropout: 0.4
    prop_dropout: 0.4
    norm: 'batch'
    nonlinear: 'GELU'
    patience: 200
