cora:
    graph_norm_type: 'laplacian'
    pair_norm_type: 'laplacian'
    pair_dis_type: 'cosine'
    pair_trunc: 0
    norm_power: [-0.5, -0.4]  # poly [-0.5]
    norm_power_len: [1000, 1000]  # poly [2708]

    nclass: 7
    nlayer: 2
    num_heads: 1
    hidden_dim: 64  # poly degree=3,5,7 verified
    epoch: 2000
    lr: 0.001  # poly 0.01
    weight_decay: 0.00001
    tran_dropout: 0.2
    feat_dropout: 0.8
    prop_dropout: 0.4
    norm: 'none'
    nonlinear: 'ReLU'
    patience: 2000
    residual: 'True'  # poly False
    is_f_tf: 'True'
citeseer:
    graph_norm_type: 'adjacency'
    pair_norm_type: 'laplacian'
    pair_dis_type: 'cosine'
    pair_trunc: 0
    norm_power: [-0.5, -0.45, -0.4]

    nclass: 6
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 2000
    lr: 0.0002
    weight_decay: 0.0001
    tran_dropout: 0.0
    feat_dropout: 0.8
    prop_dropout: 0.5
    norm: 'none'
    nonlinear: 'GELU'
    patience: 200
    residual: 'True'
    is_f_tf: 'False'
pubmed:
    graph_norm_type: 'adjacency'
    pair_norm_type: 'laplacian'
    pair_dis_type: 'cosine'
    pair_trunc: 0
    norm_power: [-0.5]

    nclass: 3
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 4000
    lr: 0.001
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.4
    prop_dropout: 0.0
    norm: 'none'
    nonlinear: 'ReLU'
    patience: 500
    residual: 'False'
    is_f_tf: 'False'
photo:
    graph_norm_type: 'laplacian'
    pair_norm_type: 'laplacian'
    pair_dis_type: 'cosine'
    pair_trunc: 0
    norm_power: [-0.45, -0.4]
    
    nclass: 8
    nlayer: 2
    num_heads: 1
    hidden_dim: 128
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0001
    tran_dropout: 0.2
    feat_dropout: 0.5
    prop_dropout: 0.2
    norm: 'none'
    nonlinear: 'GELU'
    patience: 200
    residual: 'False'
    is_f_tf: 'True'
computers:
    graph_norm_type: 'adjacency'
    pair_norm_type: 'laplacian'
    pair_dis_type: 'cosine'
    pair_trunc: 0
    norm_power: [-0.5, -0.45]

    nclass: 10
    nlayer: 2
    num_heads: 1
    hidden_dim: 256
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0001
    tran_dropout: 0.2
    feat_dropout: 0.5
    prop_dropout: 0.2
    norm: 'none'
    nonlinear: 'ReLU'
    patience: 200
    residual: 'True'
    is_f_tf: 'True'
arxiv:
    graph_norm_type: 'adjacency'
    pair_norm_type: 'laplacian'
    pair_dis_type: 'cosine'
    pair_trunc: 0
    norm_power: [-0.5, -0.4]

    nclass: 40
    nlayer: 1
    num_heads: 1
    hidden_dim: 256
    epoch: 4000
    lr: 0.005
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
    nonlinear: 'GELU'
    patience: 4000
    residual: 'True'
    is_f_tf: 'False'
products:
    graph_norm_type: 'adjacency'
    pair_norm_type: 'laplacian'
    pair_dis_type: 'cosine'
    pair_trunc: 0
    norm_power: [-0.4]

    nclass: 47
    nlayer: 1
    num_heads: 1
    hidden_dim: 192
    epoch: 4000
    lr: 0.005
    weight_decay: 0.0
    tran_dropout: 0.1
    feat_dropout: 0.1
    prop_dropout: 0.1
    norm: 'layer'
    nonlinear: 'GELU'
    patience: 4000
    residual: 'False'
    is_f_tf: 'False'
chameleon:
    graph_norm_type: 'adjacency'
    pair_norm_type: 'laplacian'
    pair_dis_type: 'cosine'
    pair_trunc: 0
    norm_power: [-0.5, -0.45]

    nclass: 5
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 2000
    lr: 0.001
    weight_decay: 0.0005
    tran_dropout: 0.2
    feat_dropout: 0.8
    prop_dropout: 0.2
    norm: 'none'
    nonlinear: 'GELU'
    patience: 1000
    residual: 'True'
    is_f_tf: 'False'
squirrel:
    graph_norm_type: 'adjacency'
    pair_norm_type: 'adjacency'
    pair_dis_type: 'cosine'
    pair_trunc: 0
    norm_power: [-0.5, -0.45]
    nclass: 5
    nlayer: 2
    num_heads: 1
    hidden_dim: 64
    epoch: 5000
    lr: 0.001
    weight_decay: 0.0001
    tran_dropout: 0.1
    feat_dropout: 0.4
    prop_dropout: 0.4
    norm: 'none'
    nonlinear: 'ReLU'
    patience: 4000
    residual: 'True'
    is_f_tf: 'True'
texas:
    graph_norm_type: 'laplacian'
    pair_norm_type: 'laplacian'
    pair_dis_type: 'cosine'
    pair_trunc: 0
    norm_power: [-0.5]

    nclass: 5
    nlayer: 2
    num_heads: 1
    hidden_dim: 32
    epoch: 1000
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.0
    feat_dropout: 0.7
    prop_dropout: 0.0
    norm: 'none'
    nonlinear: 'ReLU'
    patience: 200
    residual: 'True'
    is_f_tf: 'False'
actor:
    graph_norm_type: 'adjacency'
    pair_norm_type: 'adjacency'
    pair_dis_type: 'cosine'
    pair_trunc: 'all'
    norm_power: [-0.5]

    nclass: 5
    nlayer: 3
    num_heads: 1
    hidden_dim: 32
    epoch: 500
    lr: 0.001
    weight_decay: 0.0001
    tran_dropout: 0.5
    feat_dropout: 0.8
    prop_dropout: 0.5
    norm: 'none'
    nonlinear: 'GELU'
    patience: 200
    residual: 'True'
    is_f_tf: 'True'
penn:
    nclass: 2
    nlayer: 1
    num_heads: 1
    hidden_dim: 64
    epoch: 2000
    lr: 0.001
    weight_decay: 0.001
    tran_dropout: 0.0
    feat_dropout: 0.4
    prop_dropout: 0.4
    norm: 'batch'
    nonlinear: 'GELU'
    patience: 200
    residual: 'True'
